<?php
 /**
 * WhispyForum file - freeuniversity_phases.php
 * 
 * Free university phase configuration file
 * 
 * Specifies the current free university phase value
 * 
 * Generated by install.php at Sunday 6th of February 2011 15:05:33
 * WhispyForum
 */

 /**
 * Accepted phases are:
 *
 * 0 - before any event, everything is locked
 * 1 - performer managing: lecture specific (freeuni2) scripts are locked
 * 2 - lecture managing: performer specific (freeuni) scripts are locked
 * 3 - after every event, everything is locked
 */

define('FREEUNI_PHASE', 2); // Free university phase
?>